manifest:
  remotes:
    - name: forsongen
      url-base: https://github.com/forsongen
  projects:
    - name: zmk
      remote: forsongen
      revision: technikable
      import: app/west.yml
  self:
    path: config
